version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: economitze-docker
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
  composer:
    image: herloct/composer:1.4.2-php7.1
    command: install
    volumes:
      - .:/project